name: My Simple Action
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run my action
        run: echo "Hello, GitHub Actions!"

      - name: clang-tidy review
        uses: ZedThree/clang-tidy-review@v0.13.1

